### ISSUE TITLE
Create a website to display project information

### ISSUE THREAD

**Issue by g-fringer** [fall2021-csc510-group40/citatron-5000#18]
The goal of this issue is to develop a website that supports the points from the Software Sustainability Evaluation.

**Comment by g-fringer** [comment]
Basic site should be up to cover points 13.3, 13.4, 15.3 on the Software Sustainability Evaluation

**Comment by MrKaStep** [comment]
@g-fringer I'm getting a 404. Can you look into it?

**Comment by g-fringer** [comment]
My mistake, it was missing the path to the project itself. Try this link @MrKaStep 

https://fall2021-csc510-group40.github.io/citatron-5000/
