### ISSUE TITLE
Create DOI badge

### ISSUE THREAD

**Issue by b4443** [fall2021-csc510-group40/citatron-5000#6]
Get one from Zenodo

**Comment by g-fringer** [comment]
Created a prerelease "v0.1-prerelease" to be able to synthesize the DOI badge. Adding this to the main README now.

**Comment by g-fringer** [comment]
Badge is added, if someone can confirm visibility of the badge, this can be closed.

**Comment by MrKaStep** [comment]
LGTM

**Comment by b4443** [comment]
LGMT 👍

**Comment by b4443** [comment]
Whoops.
